import { contextBridge, ipcRenderer } from "electron";
import type { TeamRentalApi } from "../shared/contracts.js";

const api: TeamRentalApi = {
  authStatus: () => ipcRenderer.invoke("auth:status"),
  unlock: (password) => ipcRenderer.invoke("auth:unlock", password),
  setupPassword: (password) => ipcRenderer.invoke("auth:setup-password", password),
  getSecuritySettings: () => ipcRenderer.invoke("security:settings:get"),
  saveSecuritySettings: (settings) => ipcRenderer.invoke("security:settings:save", settings),
  changePassword: (currentPassword, newPassword) => ipcRenderer.invoke("security:password:change", currentPassword, newPassword),
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  dashboard: () => ipcRenderer.invoke("dashboard:get"),
  listSpaces: () => ipcRenderer.invoke("spaces:list"),
  listArchivedSpaces: () => ipcRenderer.invoke("spaces:list-archived"),
  listArchivedChildSeats: () => ipcRenderer.invoke("children:list-archived"),
  saveSpace: (input) => ipcRenderer.invoke("spaces:save", input),
  archiveSpace: (id) => ipcRenderer.invoke("spaces:archive", id),
  unarchiveSpace: (id) => ipcRenderer.invoke("spaces:unarchive", id),
  deleteArchivedSpace: (id) => ipcRenderer.invoke("spaces:delete-archived", id),
  saveChildSeat: (input) => ipcRenderer.invoke("children:save", input),
  archiveChildSeat: (id) => ipcRenderer.invoke("children:archive", id),
  restoreChildSeat: (input) => ipcRenderer.invoke("children:restore", input),
  deleteArchivedChildSeat: (id) => ipcRenderer.invoke("children:delete-archived", id),
  recordReceipt: (input) => ipcRenderer.invoke("receipts:record", input),
  renewSpace: (input) => ipcRenderer.invoke("spaces:renew", input),
  listTransactions: () => ipcRenderer.invoke("transactions:list"),
  voidReceipt: (id, reason) => ipcRenderer.invoke("receipts:void", id, reason),
  voidRenewal: (id, reason) => ipcRenderer.invoke("renewals:void", id, reason),
  listPaymentMethods: (includeArchived) => ipcRenderer.invoke("payments:list", includeArchived),
  savePaymentMethod: (input) => ipcRenderer.invoke("payments:save", input),
  setPaymentMethodArchived: (id, archived) => ipcRenderer.invoke("payments:archive", id, archived),
  deletePaymentMethod: (id) => ipcRenderer.invoke("payments:delete", id),
  listCurrencies: (includeDeleted) => ipcRenderer.invoke("currencies:list", includeDeleted),
  saveCurrency: (input) => ipcRenderer.invoke("currencies:save", input),
  deleteCurrency: (code) => ipcRenderer.invoke("currencies:delete", code),
  refreshRates: () => ipcRenderer.invoke("currencies:refresh-rates"),
  getReminderSettings: () => ipcRenderer.invoke("reminders:settings:get"),
  saveReminderSettings: (settings) => ipcRenderer.invoke("reminders:settings:save", settings),
  sendTestReminder: (kind) => ipcRenderer.invoke("reminders:test", kind),
  sendTestWindowsNotification: () => ipcRenderer.invoke("reminders:windows:test"),
  listShortcuts: () => ipcRenderer.invoke("shortcuts:list"),
  listChromeProfiles: () => ipcRenderer.invoke("shortcuts:chrome-profiles"),
  createChromeShortcut: (input) => ipcRenderer.invoke("shortcuts:create-chrome", input),
  saveShortcut: (input) => ipcRenderer.invoke("shortcuts:save", input),
  deleteShortcut: (id) => ipcRenderer.invoke("shortcuts:delete", id),
  chooseShortcutTarget: () => ipcRenderer.invoke("shortcuts:choose-target"),
  openShortcut: (id) => ipcRenderer.invoke("shortcuts:open", id),
  savePalette: (palette) => ipcRenderer.invoke("palette:save", palette),
  getBackupSettings: () => ipcRenderer.invoke("backup:settings:get"),
  saveBackupSettings: (settings) => ipcRenderer.invoke("backup:settings:save", settings),
  chooseBackupDirectory: () => ipcRenderer.invoke("backup:choose-directory"),
  runBackup: () => ipcRenderer.invoke("backup:run"),
  chooseLegacyDatabase: () => ipcRenderer.invoke("import:choose-database"),
  importLegacyDatabase: (path) => ipcRenderer.invoke("import:legacy", path),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  maximize: () => ipcRenderer.invoke("window:maximize"),
  close: () => ipcRenderer.invoke("window:close"),
};

contextBridge.exposeInMainWorld("teamRental", api);
